version: '3.8'

name: lettuce

services:
  lettuce: 
    build: 
      context: . 
      dockerfile: Dockerfile 
    env_file:
      - .env.compose  # This will take precedence over local .env file 
    ports: 
      - "8000:8000"
    networks: 
      - omop-ts-network  # Connect the existing network

networks: 
  omop-ts-network: 
    external: true 
    name: omop-ts_default 