version: '3.8'

name: lettuce

services:
  lettuce: 
    build: 
      context: . 
      dockerfile: Dockerfile 
    environment: 
      - DATABASE_URL=postgresql://postgres:password@omop-ts-omop-ts-1:5432/omop 
      - DB_HOST=omop-ts-omop-ts-1
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=omop
      - DB_PORT=5432
      - DB_SCHEMA=cdm
      - DB_VECTABLE=embeddings
      - DB_VECSIZE=384
    ports: 
      - "8000:8000"
    networks: 
      - omop-ts-network  # Connect the existing network

networks: 
  omop-ts-network: 
    external: true 
    name: omop-ts_default 