FROM python:3.12-bookworm AS builder
RUN apt-get update && \
    apt-get install --no-install-suggests --no-install-recommends --yes pipx

RUN pipx install uv 
ENV UV_CACHE_DIR=/tmp/uv_cache \
    PATH="/root/.local/bin:${PATH}"

WORKDIR /src
COPY pyproject.toml ./
RUN uv sync 

FROM python:3.12-slim-bookworm
ENV PATH="/src/.venv/bin:$PATH"
WORKDIR src
COPY --from=builder /src/.venv /src/.venv

RUN mkdir -p models  
RUN pipx install "huggingface_hub[hf_transfer]"
RUN HF_HUB_ENABLE_HF_TRANSFER=1 huggingface-cli download \ 
    "MaziyarPanahi/Meta-Llama-3.1-8B-Instruct-GGUF" \
    "Meta-Llama-3.1-8B-Instruct.Q4_K_M.gguf" \ 
    --local-dir models
ENV LOCAL_LLM="model_weights/Llama-3.1-8B"

COPY . .
EXPOSE 8000

ENTRYPOINT ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]
