name: llettuce
channels:
  - defaults
  - conda-forge
dependencies:
  - haystack-ai=2.3.1
  - huggingface_hub=0.22.2
  - python-dotenv=1.0.1
  - fastapi=0.110.3
  - uvicorn=0.29.0
  - psycopg2-binary=2.9.9
  - streamlit=1.36.0
  - pytorch=2.3.0
  - rapidfuzz=3.5.2
  - openssl=3.1.4
  - sseclient-py=1.8.0
  - sqlalchemy=2.0.30
  - numpy=1.26.4
  - pip
  - pip:
      - llama-cpp-haystack==0.4.0
