name: Check Container Builds

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Build Docker image
        uses: docker/build-push-action@v5.3.0
        env: 
          BUILDX_DEBUG: 1  
        with:
          context: ./lettuce 
          file: ./lettuce/Dockerfile
          push: false
          platforms: linux/amd64
          load: true
          tags: lettuce:test 
      
      - name: Test container startup 
        run: | 
          # Start container in background
          docker run -d --name lettuce-test lettuce:test

          if docker ps | grep lettuce-test; then
            echo "Container started successfully"
          else
            echo "Container failed to start!"
            docker logs lettuce-test
            exit 1
          fi
          
          docker stop lettuce-test
          docker rm lettuce-test
    
