name: "Check PR title"

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  main:
    uses: health-informatics-uon/workflows/.github/workflows/pr-title.yml@87876cc292cff65a17334caf4d18d42ae62baab3 # v 1.5.2
    permissions:
      pull-requests: read
