name: Run Tests

on:
  pull_request:

  push:
    branches:
      - deliverable/implement-small-omop-db-for-ci-tests

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    env:
      SKIP_DATABASE_TESTS: false 
      SKIP_LLM_TESTS: true 
      SKIP_EVAL_TESTS: true 


    steps:
      - name: Checkout omop-lite repository
        uses: actions/checkout@v4
        with:
          repository: Health-Informatics-UoN/omop-lite  
          path: omop-lite
          ref: adding-test-data 

      - name: Checkout lettuce repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}  

      - name: Move test data from synthetic into data
        run: |
          mkdir omop-lite/data
          mv omop-lite/synthetic/* omop-lite/data/

      - name: Start omop-ts Docker services
        run: |         
          # Start the database service
          docker compose -f omop-lite/compose-omop-ts.yml up -d
          
          # Give some time for database to initialize
          echo "Waiting for database to initialize..."
          sleep 15
      
      - name: Start lettuce Docker services
        run: |
          # Start the lettuce service with our compose file
          docker compose -f lettuce/compose.yaml up -d
          
          # Give some time for services to initialize
          sleep 15
          
          # Verify all services are running
          docker ps

      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.16"
          enable-cache: true
          cache-dependency-glob: "lettuce/uv.lock"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "lettuce/.python-version" 

      - name: uv sync
        run: uv sync --all-extras 
        working-directory: lettuce

      - name: Run tests
        run: |
          set -e
          uv run pytest tests --junitxml=pytest.xml --cov-report=term-missing:skip-covered --cov=lettuce tests | tee pytest-coverage.txt
          test ${PIPESTATUS[0]} -eq 0
        working-directory: lettuce 
        env:
          SKIP_DATABASE_TESTS: false
          SKIP_LLM_TESTS: true 
          SKIP_EVAL_TESTS: true 
      
      - name: Cleanup Docker services
        if: always()
        run: |
          # Cleanup all services to prevent resource issues
          docker compose -f lettuce/docker-compose.yml down
          docker compose -f omop-ts/docker-compose.yml down
          docker network rm omop-ts_default || true

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@81882822c5b22af01f91bd3eacb1cefb6ad73dc2
        with:
          pytest-coverage-path: pytest-coverage.txt
          junitxml-path: pytest.xml
        


