name: Check Container Builds

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Remove unnecessary files
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Check out the repo
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build Docker image
        uses: docker/build-push-action@v7.2.0
        env: 
          BUILDX_DEBUG: 1  
        with:
          context: ./lettuce 
          file: ./lettuce/Dockerfile
          push: false
          platforms: linux/amd64
          load: true
          tags: lettuce:test 
      
      - name: Test container startup 
        run: | 
          # Start container in background
          docker run -d --name lettuce-test lettuce:test

          if docker ps | grep lettuce-test; then
            echo "Container started successfully"
          else
            echo "Container failed to start!"
            docker logs lettuce-test
            exit 1
          fi
          
          docker stop lettuce-test
          docker rm lettuce-test
    
