# Builds and publishes a Docker container image with pre-loaded LLaMA-3.1-8B weights for the Lettuce project.
# This workflow is manually triggered, tags the image as a development release with the 'dev-weights-llama-3.1-8B' prefix,
# and pushes it to GitHub Container Registry (ghcr.io).

name: Build and publish pre-loaded weights image to GHCR and deploy to Azure

on:
  push:
    branches:
      - main
        
env:
  image-name: lettuce
  repo-owner: ${{ github.repository_owner }}
  registry: ghcr.io
  model-name: llama-3.1-8B


jobs:
  build-and-publish-lettuce-weights-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    
    outputs:
      image-sha: ${{ steps.tag.outputs.image_sha }}

    steps:
      - name: Free up disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android  
          sudo rm -rf /opt/ghc
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker system prune -af
          df -h

      - name: Check out the repo
        uses: actions/checkout@v4

      #- name: Set up QEMU
      #  uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      - name: Docker Login
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: SebRollen/toml-action@v1.2.0
        id: read_version
        with:
          file: "lettuce/pyproject.toml"
          field: project.version

      - name: Docker Metadata action
        id: meta
        uses: docker/metadata-action@v5.5.1
        env:
          DOCKER_METADATA_ANNOTATIONS_LEVELS: manifest,index
        with:
          images: ${{ env.registry }}/${{ env.repo-owner }}/${{ env.image-name }}
          # Tag notes:
          # - RFC3339 (standardised format for timestamps) is not suitable for docker tags, so we squash the date
          # - We only tag the short (7-char prefixed) commit hashes as this is a dev image 
          # - `edge` represents latest main branch commit (potentially unstable)
          tags: |
            type=sha,prefix=dev-weights-${{ env.model-name }}-
            type=raw,value=dev-weights-${{ env.model-name }}-{{date 'YYYYMMDDHHmmss[Z]'}}
            dev-weights-${{ env.model-name }}-edge
          # Label notes:
          # - Static labels are applied in the Dockerfile
          # - Date format in `org.opencontainers.image.created` must be RFC3339
          # - version should be considered a semver candidate only, unless revision aligns with a git tag
          labels: |
            org.opencontainers.image.revision={{sha}}
            org.opencontainers.image.version=${{ steps.read_version.outputs.value }}
            org.opencontainers.image.created={{date 'YYYY-MM-DD HH:mm:ss[Z]'}}
          # TODO: More Annotations may be desirable instead of labels for some metadata,
          # since we produce multiarch images
          annotations: |
            org.opencontainers.image.description=lettuce
      
      - name: Extract image tag
        id: tag
        run: |
          sha=$(echo "$DOCKER_METADATA_OUTPUT_TAGS" | tr ' ' '\n' | grep -E "dev-weights-llama-3\.1-8B-[a-f0-9]{7}$" | grep -oE "[a-f0-9]{7}")
          echo "image_sha=$sha" >> $GITHUB_OUTPUT

      - name: Build and push Docker images
        uses: docker/build-push-action@v5.3.0
        with:
          context: "./lettuce"
          file: "lettuce/Dockerfile.model"
          push: true
          platforms: linux/amd64 # ,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
                  
      - name: Delete old package versions
        uses: actions/delete-package-versions@v4
        with:
          package-name: lettuce
          package-type: container
          min-versions-to-keep: 10
          token: ${{ secrets.GITHUB_TOKEN }}
    
  deploy-lettuce-dev: 
    runs-on: ubuntu-latest
    needs: [build-and-publish-lettuce-weights-image]
    
    steps:      
      # Main deployment
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ env.registry }}/${{ env.repo-owner }}/${{ env.image-name }}:dev-weights-${{ env.model-name }}-${{ needs.build-and-publish-lettuce-weights-image.outputs.image-sha }}
      